server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*log

  - job_name: nginx
    static_configs:
    - targets:
        - localhost
      labels:
        job: nginx
        __path__: /var/log/nginx/*log

  - job_name: sanvi-backend
    static_configs:
    - targets:
        - localhost
      labels:
        job: sanvi-backend
        environment: production
        __path__: /var/log/sanvi-backend/*.log
    
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            timestamp: timestamp
            trace_id: trace_id
            span_id: span_id
      - labels:
          level:
          trace_id:
          span_id:
      - timestamp:
          source: timestamp
          format: RFC3339Nano

  - job_name: sanvi-backend-staging
    static_configs:
    - targets:
        - localhost
      labels:
        job: sanvi-backend
        environment: staging
        __path__: /var/log/sanvi-backend-staging/*.log
    
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            timestamp: timestamp
            trace_id: trace_id
            span_id: span_id
      - labels:
          level:
          trace_id:
          span_id:
      - timestamp:
          source: timestamp
          format: RFC3339Nano
